### ISSUE TITLE
julia-vterm-switch-to-repl-buffer does not reuse the REPL already open in another frame

### ISSUE THREAD

**Issue by shg** [shg/julia-vterm.el#4]

**Comment by cobac** [comment]
This problem is solved by setting 

```elisp
  (setq display-buffer-reuse-frames t)
```

It's obsolete, but hey it works 🙃

**Comment by shg** [comment]
Yeah, I confirmed that works. I'm thinking to implement a package-specific option for this when I have time. But it will not happen soon... So it's good to use that workaround for now. Thank you!

**Comment by shg** [comment]
Solved with c5f67a372777bb6a855ba2a89228a713c8dda957. Currently existing window is always reused.

**Comment by shg** [comment]
The variable `display-buffer-alist` is a user-customizable option but the above code ignores it. The code has been removed with a3ab6cef6ca938ba446f357b9618572115bf3721.
