### ISSUE TITLE
Option to set julia executable 

### ISSUE THREAD

**Issue by MasonProtter** [shg/julia-vterm.el#8]
I'm not sure how `ob-julia-vterm` is finding the julia executable, but it's not working for me. I built julia from source and it's located at
```
~/julia/./julia
```
When I try and activate `julia-vterm`, I get the message 
```julia
vterm-send-string: Process vterm not running
/bin/sh: line 1: exec: julia: cannot execute: Is a directory
```

It'd be good if there was an option I could set for the julia path that `julia-vterm` uses (and same for `ob-julia-vterm`)

**Comment by shg** [comment]
You need to set `julia-vterm-repl-program` variable if Julia is not in PATH.

Julia-vterm opens a Julia REPL using vterm. VTerm runs the Julia program  via `sh` command invoked with `make-process`. So the `sh` should be able to find Julia. You can set its absolute path to `julia-vterm-repl-program`, or you should set PATH environment variable in Emacs.
